# Setup Ubuntu repository 
- block:
    - name: Install required packages
      apt: 
        name: "{{ item }}" 
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add the package repositories 1
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        
    - name: Add the package repositories 1
      shell: apt-key fingerprint 0EBFCD88

    - name: Add the package repositories 1
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: Install docker-ce
      apt:
        name: docker-ce
        update_cache: yes
  when: ansible_distribution == "Ubuntu"

# Setup CentOS repository 
- block:
    - name: Uninstall old versions
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-selinux
        - docker-engine-selinux
        - docker-engine

    - name: Install required packages
      yum: 
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Add the package repositories
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install docker-ce
      yum:
        name: docker-ce
        update_cache: yes

    - name: Start docker-ce
      shell: systemctl start docker
  when: ansible_distribution == "CentOS"

